[package]
name = "victrix"
version = "0.1.0"
authors = ["ever <ever1337@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.ggez]
opt-level = 1

[dependencies]
ggez = "0.5.1"
log = "0.4.8"
env_logger = "0.7.1"
gfx_glyph = "0.16.0"
